stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml

lint:
  image: node:lts
  before_script:
    - npm install --progress=false
  stage: test
  allow_failure: true
  script: npm run lint

build:
  stage: build
  script: docker build .

build_dist:
  image: node:lts
  stage: build
  before_script:
    - npm install --progress=false
  script: npm run build
  artifacts:
    expire_in: 1 week
    paths: 
      - dist
